sudo: required
services:
- docker
language: go
go:
- '1.11'
env:
  global:
  - PATH=/home/travis/gopath/bin:$PATH DEBIAN_FRONTEND=noninteractive
  - secure: N7KZpqx7uxdo+sJP1OMiQOimTv1W7XcIf6s9HoGvYr8erM3HP22tmZoOxu1el0aXSCp6oUb8RpnK/VILtVgDS8/DwjoxXCbCnDuWrY854gzsmDEgh5Okrm3Mt4BBGGGNeWiD+GWrZ1nd2T5VIdIh9IwqzTihqJp+W1n2ZxJtoEQXEPfJEqdMb0mvdlcJ6P9KC5G382DGfji5zMbvXw8hTZvNXJQIcYIrZGFz7V4eobyUMNOR6WzyVIZexZB6J9I7xxoVtObLQEI13wfJRQNw/trSZrw1NwZRB41r0WUurHP0Vfi9utiup5k3WBWcim/qYAHO7BtF6ZbQYlkSFViZGWd1LSzMEg67AjMiXxtAeA9iX/+Qu6i7jGoMnVGfp1X2BDwZqHGWn9REnbd2k50nxN/Dgez7STev1UI/XA/F6wpq4c1fMnnSqD4JFUrmAK0rgw4CGc5RU+mBIvLPROuNMNJJEE7inZKLDpZWxMM3y1FZWOMVmgncxHj7kNSdneg51YSvfiK3XhVqVOO7pZ1WiWGmaF2gpfxTQlvQYTSSgLszPCdF2w/C/HvWYIMOwv4rxPlt4+MFeumJzUDAFNHvlQA8SHqZQIurCWcdaflvLECqnhZI1cbx3r4kZ1cjGWIRANSeHlOLPBb1N06ykop9rYVt1z9ODNJkrNr0Nat/WuI=
before_install:
- make tools
script:
- make golint test
before_deploy:
- make docker-build
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: bin/*
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  on:
    tags: true
notifications:
  slack:
    secure: BNxWprYckosLBlaLn7XUt7ozbF5HWZvWMUUSOgw7JA5qWK3PCbwT0fCD/VwM/pKWLaFZeFgSlg1NopZwGKZ6RTX9WrJBXy6Eyurzk/9ZHQ5CAqZhb5HP/MdFWa6DApWmNO7GXJf2J0qYEewEjA+Y7iatADfy5oHg0VN2n1Dyz7gP3iShP9BGt4ewEpStg7qhA2De+in4NGWJEOGiCNCyxhIgQnSX42VYSFfHgipZEv/4dN+P9iBouPQMvP4WjqYLW6Zp4XXTr51HNHhrJuDUgyhRHeR5OTOLJEgSiXYeCNg5j8Au6Y7mAihuMtQGdejYRlMZs2s2ALpwkTYnIV01tqbU5YsmXq4nseiBdzuarJuejoMBya/eatOGesnHQ1CgyT5i5o2xAg3L6BlE7mDAyjFAyJOQFEV6PK2SW8sszkbwdOXnvAoVyV6oU2ze2QeD0dhvMLQhUQQ27DIkjzEnpFVpeFYhcgWUyh3vTzgEyVInBfdvbCpZOVwtJyrqJW2Y+eX06yU8TmTdgVlPMQjuXM2UTC9feWTG+7A2EQpwkRg2ltWr9zKVUPOlLEl3s0vAUlSTDI/ei/JLVV9jkDK3QzxNivLb7Rtg0z2XmJRI6R/1cO9ATD5LlcaobOvLDjQM6kuSu9T7eF03Qq4Kz30IC82dkVIeQA41llW4K3d5GG0=
